DB-step4
NurGuru/Dictionary pull request #5
Opened 2023-04-11 21:02 UTC by NurGuru

подскажи пожалуйста как функцию сохранения количества правильных ответов оформить
и в остальном правильно все?

2023-04-12 12:32 UTC, ievetrov requested changes

2023-04-12 12:32 UTC, ievetrov commented on src/main/kotlin/fiels.kt
> +//        wordsFile.writeText()  что-то не соображу как правильно эту функцию оформить
У тебя есть список слов, пройдись по нему циклом и запиши каждое слово в файл в виде строки:
```Kotlin
"${word.original}|${word.translate}|${word.correctAnswersCount}\n"
```

2023-04-12 20:21 UTC, ievetrov requested changes

2023-04-12 20:21 UTC, ievetrov commented on src/main/kotlin/fiels.kt
> +//        wordsFile.writeText()  что-то не соображу как правильно эту функцию оформить
а комент кому оставил? )

2023-04-12 20:44 UTC, NurGuru commented on src/main/kotlin/fiels.kt
> +//        wordsFile.writeText()  что-то не соображу как правильно эту функцию оформить
блин)

2023-04-13 10:38 UTC, ievetrov approved these changes

2023-04-13 14:40 UTC, merged